apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pivg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-pivg
    app.kubernetes.io/part-of: pet-clinic-e2e-uehjtlhboo
  name: devfile-sample-code-with-quarkus-pivg
  namespace: has-e2e-public-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pivg
status:
  loadBalancer: {}
